### ISSUE TITLE
Sounds still needed

### ISSUE THREAD

**Issue by Daskie** [jaafersheriff/BattleRoyale#89]
- player death noise
- game over noise
- wave complete noise

**Comment by alacardnightmare** [comment]
Enemy Death
Italian Background x3

**Comment by alacardnightmare** [comment]
Asian x3
American x3

**Comment by alacardnightmare** [comment]
Victory
Water Fountain
Game over

**Comment by alacardnightmare** [comment]
footstep
enemy damaged grunt x3
